### ISSUE TITLE
DEVELOP 05: Domain Modeling

### ISSUE THREAD

**Issue by jerry914** [SOA-NullSpace/meal-decoder-api#10]
## Task

- [x] Update the description of your project
- [x] Create the domain objects you might need
- [x] Develop your Web Application
- [x] Deploy your Web application to Heroku (AWS) 

Your application on Render is wonderful! 👍

## RuboCop/Code Smell Offenses

- **Organize your files**: Please move `meal_decoder.rb` from the root directory to an appropriate folder, or delete it if it's no longer needed after testing.

Fantastic job so far—keep up the great momentum!

**Comment by hedgehog-menn** [comment]
Really appreciate your review, Thank you😊🙏

**Comment by soumyaray** [comment]
https://github.com/SOA-NullSpace/meal-decoder-api/blob/b14a8e023bcea2e178b535e4b7287281a8b53670/app/domain/entities/ingredient.rb#L18

Hey folks, in your Ingredient entity, the parsing logic seems more appropriate for a mapper than an entity. Let me know if you feel otherwise?

**Comment by hedgehog-menn** [comment]
You're correct. I'm agree it should be moved into mapper.
